// proto/shipment.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: shipment.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipmentStatus int32

const (
	ShipmentStatus_IN_TRANSIT  ShipmentStatus = 0
	ShipmentStatus_DELIVERED   ShipmentStatus = 1
	ShipmentStatus_PENDING     ShipmentStatus = 2
	ShipmentStatus_PRE_TRANSIT ShipmentStatus = 3
	ShipmentStatus_CANCELLED   ShipmentStatus = 4
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "IN_TRANSIT",
		1: "DELIVERED",
		2: "PENDING",
		3: "PRE_TRANSIT",
		4: "CANCELLED",
	}
	ShipmentStatus_value = map[string]int32{
		"IN_TRANSIT":  0,
		"DELIVERED":   1,
		"PENDING":     2,
		"PRE_TRANSIT": 3,
		"CANCELLED":   4,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipment_proto_enumTypes[0].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_shipment_proto_enumTypes[0]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

type GetShipmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=shipment.ShipmentStatus" json:"status,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentsRequest) Reset() {
	*x = GetShipmentsRequest{}
	mi := &file_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentsRequest) ProtoMessage() {}

func (x *GetShipmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentsRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentsRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *GetShipmentsRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetShipmentsRequest) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_IN_TRANSIT
}

func (x *GetShipmentsRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *GetShipmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetShipmentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetShipmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipments     []*Shipment            `protobuf:"bytes,1,rep,name=shipments,proto3" json:"shipments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentsResponse) Reset() {
	*x = GetShipmentsResponse{}
	mi := &file_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentsResponse) ProtoMessage() {}

func (x *GetShipmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentsResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentsResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *GetShipmentsResponse) GetShipments() []*Shipment {
	if x != nil {
		return x.Shipments
	}
	return nil
}

type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Eta           string                 `protobuf:"bytes,3,opt,name=eta,proto3" json:"eta,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=shipment.ShipmentStatus" json:"status,omitempty"`
	Carrier       *Carrier               `protobuf:"bytes,5,opt,name=carrier,proto3" json:"carrier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *CreateShipmentRequest) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_IN_TRANSIT
}

func (x *CreateShipmentRequest) GetCarrier() *Carrier {
	if x != nil {
		return x.Carrier
	}
	return nil
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type Shipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Eta           string                 `protobuf:"bytes,4,opt,name=eta,proto3" json:"eta,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=shipment.ShipmentStatus" json:"status,omitempty"`
	Carrier       *Carrier               `protobuf:"bytes,6,opt,name=carrier,proto3" json:"carrier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *Shipment) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_IN_TRANSIT
}

func (x *Shipment) GetCarrier() *Carrier {
	if x != nil {
		return x.Carrier
	}
	return nil
}

type Carrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TrackingUrl   string                 `protobuf:"bytes,2,opt,name=tracking_url,json=trackingUrl,proto3" json:"tracking_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Carrier) Reset() {
	*x = Carrier{}
	mi := &file_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Carrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Carrier) ProtoMessage() {}

func (x *Carrier) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Carrier.ProtoReflect.Descriptor instead.
func (*Carrier) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *Carrier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Carrier) GetTrackingUrl() string {
	if x != nil {
		return x.TrackingUrl
	}
	return ""
}

var File_shipment_proto protoreflect.FileDescriptor

const file_shipment_proto_rawDesc = "" +
	"\n" +
	"\x0eshipment.proto\x12\bshipment\"\xaf\x01\n" +
	"\x13GetShipmentsRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.shipment.ShipmentStatusR\x06status\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"H\n" +
	"\x14GetShipmentsResponse\x120\n" +
	"\tshipments\x18\x01 \x03(\v2\x12.shipment.ShipmentR\tshipments\"\xc2\x01\n" +
	"\x15CreateShipmentRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x10\n" +
	"\x03eta\x18\x03 \x01(\tR\x03eta\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.shipment.ShipmentStatusR\x06status\x12+\n" +
	"\acarrier\x18\x05 \x01(\v2\x11.shipment.CarrierR\acarrier\"H\n" +
	"\x16CreateShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"\xc5\x01\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x10\n" +
	"\x03eta\x18\x04 \x01(\tR\x03eta\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.shipment.ShipmentStatusR\x06status\x12+\n" +
	"\acarrier\x18\x06 \x01(\v2\x11.shipment.CarrierR\acarrier\"@\n" +
	"\aCarrier\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ftracking_url\x18\x02 \x01(\tR\vtrackingUrl*<\n" +
	"\x0eShipmentStatus\x12\x0e\n" +
	"\n" +
	"IN_TRANSIT\x10\x00\x12\r\n" +
	"\tDELIVERED\x10\x01\x12\v\n" +
	"\aPENDING\x10\x022\xb5\x01\n" +
	"\x0fShipmentService\x12M\n" +
	"\fGetShipments\x12\x1d.shipment.GetShipmentsRequest\x1a\x1e.shipment.GetShipmentsResponse\x12S\n" +
	"\x0eCreateShipment\x12\x1f.shipment.CreateShipmentRequest\x1a .shipment.CreateShipmentResponseB8Z6github.com/Tanmoy095/LogiSynapse/graphql-gateway/protob\x06proto3"

var (
	file_shipment_proto_rawDescOnce sync.Once
	file_shipment_proto_rawDescData []byte
)

func file_shipment_proto_rawDescGZIP() []byte {
	file_shipment_proto_rawDescOnce.Do(func() {
		file_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)))
	})
	return file_shipment_proto_rawDescData
}

var file_shipment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shipment_proto_goTypes = []any{
	(ShipmentStatus)(0),            // 0: shipment.ShipmentStatus
	(*GetShipmentsRequest)(nil),    // 1: shipment.GetShipmentsRequest
	(*GetShipmentsResponse)(nil),   // 2: shipment.GetShipmentsResponse
	(*CreateShipmentRequest)(nil),  // 3: shipment.CreateShipmentRequest
	(*CreateShipmentResponse)(nil), // 4: shipment.CreateShipmentResponse
	(*Shipment)(nil),               // 5: shipment.Shipment
	(*Carrier)(nil),                // 6: shipment.Carrier
}
var file_shipment_proto_depIdxs = []int32{
	0, // 0: shipment.GetShipmentsRequest.status:type_name -> shipment.ShipmentStatus
	5, // 1: shipment.GetShipmentsResponse.shipments:type_name -> shipment.Shipment
	0, // 2: shipment.CreateShipmentRequest.status:type_name -> shipment.ShipmentStatus
	6, // 3: shipment.CreateShipmentRequest.carrier:type_name -> shipment.Carrier
	5, // 4: shipment.CreateShipmentResponse.shipment:type_name -> shipment.Shipment
	0, // 5: shipment.Shipment.status:type_name -> shipment.ShipmentStatus
	6, // 6: shipment.Shipment.carrier:type_name -> shipment.Carrier
	1, // 7: shipment.ShipmentService.GetShipments:input_type -> shipment.GetShipmentsRequest
	3, // 8: shipment.ShipmentService.CreateShipment:input_type -> shipment.CreateShipmentRequest
	2, // 9: shipment.ShipmentService.GetShipments:output_type -> shipment.GetShipmentsResponse
	4, // 10: shipment.ShipmentService.CreateShipment:output_type -> shipment.CreateShipmentResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_shipment_proto_init() }
func file_shipment_proto_init() {
	if File_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_proto_goTypes,
		DependencyIndexes: file_shipment_proto_depIdxs,
		EnumInfos:         file_shipment_proto_enumTypes,
		MessageInfos:      file_shipment_proto_msgTypes,
	}.Build()
	File_shipment_proto = out.File
	file_shipment_proto_goTypes = nil
	file_shipment_proto_depIdxs = nil
}
