// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/shipment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Carrier details
type Carrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TrackingUrl   string                 `protobuf:"bytes,2,opt,name=tracking_url,json=trackingUrl,proto3" json:"tracking_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Carrier) Reset() {
	*x = Carrier{}
	mi := &file_proto_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Carrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Carrier) ProtoMessage() {}

func (x *Carrier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Carrier.ProtoReflect.Descriptor instead.
func (*Carrier) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *Carrier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Carrier) GetTrackingUrl() string {
	if x != nil {
		return x.TrackingUrl
	}
	return ""
}

// Define structure for shipment operation....
type Shipment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin         string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination    string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Eta            string                 `protobuf:"bytes,4,opt,name=eta,proto3" json:"eta,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Carrier        *Carrier               `protobuf:"bytes,6,opt,name=carrier,proto3" json:"carrier,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,7,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Length         float64                `protobuf:"fixed64,8,opt,name=length,proto3" json:"length,omitempty"`
	Width          float64                `protobuf:"fixed64,9,opt,name=width,proto3" json:"width,omitempty"`
	Height         float64                `protobuf:"fixed64,10,opt,name=height,proto3" json:"height,omitempty"`
	Weight         float64                `protobuf:"fixed64,11,opt,name=weight,proto3" json:"weight,omitempty"`
	Unit           string                 `protobuf:"bytes,12,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_proto_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *Shipment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Shipment) GetCarrier() *Carrier {
	if x != nil {
		return x.Carrier
	}
	return nil
}

func (x *Shipment) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Shipment) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Shipment) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Shipment) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Shipment) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Shipment) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// Rate message for carrier rates
// Why: Supports rate comparison feature
type Rate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Carrier       string                 `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`                                   // e.g., "fedex"
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`                                   // e.g., "FedEx Ground"
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`                                   // Cost in USD
	EstimatedDays int32                  `protobuf:"varint,4,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"` // Delivery time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_proto_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *Rate) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *Rate) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Rate) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Rate) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

// GetShipmentsRequest for fetching shipments
// Why: Supports filtered queries with pagination
type GetShipmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentsRequest) Reset() {
	*x = GetShipmentsRequest{}
	mi := &file_proto_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentsRequest) ProtoMessage() {}

func (x *GetShipmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentsRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *GetShipmentsRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetShipmentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetShipmentsRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *GetShipmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetShipmentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetShipmentResponse  returns list of shipments
// Provide query results to client
type GetShipmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipments     []*Shipment            `protobuf:"bytes,1,rep,name=shipments,proto3" json:"shipments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentsResponse) Reset() {
	*x = GetShipmentsResponse{}
	mi := &file_proto_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentsResponse) ProtoMessage() {}

func (x *GetShipmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentsResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *GetShipmentsResponse) GetShipments() []*Shipment {
	if x != nil {
		return x.Shipments
	}
	return nil
}

// CreateShipmentRequest for creating shipment
// Define input for creating operations
type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Eta           string                 `protobuf:"bytes,3,opt,name=eta,proto3" json:"eta,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Carrier       *Carrier               `protobuf:"bytes,5,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Length        float64                `protobuf:"fixed64,6,opt,name=length,proto3" json:"length,omitempty"`
	Width         float64                `protobuf:"fixed64,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,8,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float64                `protobuf:"fixed64,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Unit          string                 `protobuf:"bytes,10,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_proto_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *CreateShipmentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateShipmentRequest) GetCarrier() *Carrier {
	if x != nil {
		return x.Carrier
	}
	return nil
}

func (x *CreateShipmentRequest) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CreateShipmentRequest) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateShipmentRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateShipmentRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateShipmentRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// CreateShipmentResponse returns created shipment
// return created shipment to client
type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_proto_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

// UpdateShipmentRequest for updating Shipment
// Define input for  update operation
type UpdateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Eta           string                 `protobuf:"bytes,4,opt,name=eta,proto3" json:"eta,omitempty"`
	Carrier       *Carrier               `protobuf:"bytes,5,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Length        float64                `protobuf:"fixed64,6,opt,name=length,proto3" json:"length,omitempty"`
	Width         float64                `protobuf:"fixed64,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,8,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float64                `protobuf:"fixed64,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Unit          string                 `protobuf:"bytes,10,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentRequest) Reset() {
	*x = UpdateShipmentRequest{}
	mi := &file_proto_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentRequest) ProtoMessage() {}

func (x *UpdateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *UpdateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *UpdateShipmentRequest) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *UpdateShipmentRequest) GetCarrier() *Carrier {
	if x != nil {
		return x.Carrier
	}
	return nil
}

func (x *UpdateShipmentRequest) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *UpdateShipmentRequest) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UpdateShipmentRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UpdateShipmentRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateShipmentRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// return updated results to client
type UpdateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentResponse) Reset() {
	*x = UpdateShipmentResponse{}
	mi := &file_proto_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentResponse) ProtoMessage() {}

func (x *UpdateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type DeleteShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShipmentRequest) Reset() {
	*x = DeleteShipmentRequest{}
	mi := &file_proto_shipment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShipmentRequest) ProtoMessage() {}

func (x *DeleteShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShipmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShipmentResponse) Reset() {
	*x = DeleteShipmentResponse{}
	mi := &file_proto_shipment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShipmentResponse) ProtoMessage() {}

func (x *DeleteShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShipmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteShipmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteShipmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get_Rate_Request for fetching carrier rates
// input for rate comparison
type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Length        float64                `protobuf:"fixed64,3,opt,name=length,proto3" json:"length,omitempty"`
	Width         float64                `protobuf:"fixed64,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,5,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Unit          string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_proto_shipment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{11}
}

func (x *GetRatesRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetRatesRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *GetRatesRequest) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetRatesRequest) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetRatesRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetRatesRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GetRatesRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// Provide rate options to client
type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*Rate                `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_proto_shipment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{12}
}

func (x *GetRatesResponse) GetRates() []*Rate {
	if x != nil {
		return x.Rates
	}
	return nil
}

var File_proto_shipment_proto protoreflect.FileDescriptor

const file_proto_shipment_proto_rawDesc = "" +
	"\n" +
	"\x14proto/shipment.proto\x12\bshipment\"@\n" +
	"\aCarrier\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ftracking_url\x18\x02 \x01(\tR\vtrackingUrl\"\xc6\x02\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x10\n" +
	"\x03eta\x18\x04 \x01(\tR\x03eta\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12+\n" +
	"\acarrier\x18\x06 \x01(\v2\x11.shipment.CarrierR\acarrier\x12'\n" +
	"\x0ftracking_number\x18\a \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06length\x18\b \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\t \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\v \x01(\x01R\x06weight\x12\x12\n" +
	"\x04unit\x18\f \x01(\tR\x04unit\"y\n" +
	"\x04Rate\x12\x18\n" +
	"\acarrier\x18\x01 \x01(\tR\acarrier\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12%\n" +
	"\x0eestimated_days\x18\x04 \x01(\x05R\restimatedDays\"\x95\x01\n" +
	"\x13GetShipmentsRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"H\n" +
	"\x14GetShipmentsResponse\x120\n" +
	"\tshipments\x18\x01 \x03(\v2\x12.shipment.ShipmentR\tshipments\"\x9a\x02\n" +
	"\x15CreateShipmentRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x10\n" +
	"\x03eta\x18\x03 \x01(\tR\x03eta\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12+\n" +
	"\acarrier\x18\x05 \x01(\v2\x11.shipment.CarrierR\acarrier\x12\x16\n" +
	"\x06length\x18\x06 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\a \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\t \x01(\x01R\x06weight\x12\x12\n" +
	"\x04unit\x18\n" +
	" \x01(\tR\x04unit\"H\n" +
	"\x16CreateShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"\x92\x02\n" +
	"\x15UpdateShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x10\n" +
	"\x03eta\x18\x04 \x01(\tR\x03eta\x12+\n" +
	"\acarrier\x18\x05 \x01(\v2\x11.shipment.CarrierR\acarrier\x12\x16\n" +
	"\x06length\x18\x06 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\a \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\t \x01(\x01R\x06weight\x12\x12\n" +
	"\x04unit\x18\n" +
	" \x01(\tR\x04unit\"H\n" +
	"\x16UpdateShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"'\n" +
	"\x15DeleteShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteShipmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbd\x01\n" +
	"\x0fGetRatesRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\"8\n" +
	"\x10GetRatesResponse\x12$\n" +
	"\x05rates\x18\x01 \x03(\v2\x0e.shipment.RateR\x05rates2\xa2\x03\n" +
	"\x0fShipmentService\x12M\n" +
	"\fGetShipments\x12\x1d.shipment.GetShipmentsRequest\x1a\x1e.shipment.GetShipmentsResponse\x12S\n" +
	"\x0eCreateShipment\x12\x1f.shipment.CreateShipmentRequest\x1a .shipment.CreateShipmentResponse\x12S\n" +
	"\x0eUpdateShipment\x12\x1f.shipment.UpdateShipmentRequest\x1a .shipment.UpdateShipmentResponse\x12S\n" +
	"\x0eDeleteShipment\x12\x1f.shipment.DeleteShipmentRequest\x1a .shipment.DeleteShipmentResponse\x12A\n" +
	"\bGetRates\x12\x19.shipment.GetRatesRequest\x1a\x1a.shipment.GetRatesResponseB?Z=github.com/Tanmoy095/LogiSynapse/shipment-service/proto;protob\x06proto3"

var (
	file_proto_shipment_proto_rawDescOnce sync.Once
	file_proto_shipment_proto_rawDescData []byte
)

func file_proto_shipment_proto_rawDescGZIP() []byte {
	file_proto_shipment_proto_rawDescOnce.Do(func() {
		file_proto_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shipment_proto_rawDesc), len(file_proto_shipment_proto_rawDesc)))
	})
	return file_proto_shipment_proto_rawDescData
}

var file_proto_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_shipment_proto_goTypes = []any{
	(*Carrier)(nil),                // 0: shipment.Carrier
	(*Shipment)(nil),               // 1: shipment.Shipment
	(*Rate)(nil),                   // 2: shipment.Rate
	(*GetShipmentsRequest)(nil),    // 3: shipment.GetShipmentsRequest
	(*GetShipmentsResponse)(nil),   // 4: shipment.GetShipmentsResponse
	(*CreateShipmentRequest)(nil),  // 5: shipment.CreateShipmentRequest
	(*CreateShipmentResponse)(nil), // 6: shipment.CreateShipmentResponse
	(*UpdateShipmentRequest)(nil),  // 7: shipment.UpdateShipmentRequest
	(*UpdateShipmentResponse)(nil), // 8: shipment.UpdateShipmentResponse
	(*DeleteShipmentRequest)(nil),  // 9: shipment.DeleteShipmentRequest
	(*DeleteShipmentResponse)(nil), // 10: shipment.DeleteShipmentResponse
	(*GetRatesRequest)(nil),        // 11: shipment.GetRatesRequest
	(*GetRatesResponse)(nil),       // 12: shipment.GetRatesResponse
}
var file_proto_shipment_proto_depIdxs = []int32{
	0,  // 0: shipment.Shipment.carrier:type_name -> shipment.Carrier
	1,  // 1: shipment.GetShipmentsResponse.shipments:type_name -> shipment.Shipment
	0,  // 2: shipment.CreateShipmentRequest.carrier:type_name -> shipment.Carrier
	1,  // 3: shipment.CreateShipmentResponse.shipment:type_name -> shipment.Shipment
	0,  // 4: shipment.UpdateShipmentRequest.carrier:type_name -> shipment.Carrier
	1,  // 5: shipment.UpdateShipmentResponse.shipment:type_name -> shipment.Shipment
	2,  // 6: shipment.GetRatesResponse.rates:type_name -> shipment.Rate
	3,  // 7: shipment.ShipmentService.GetShipments:input_type -> shipment.GetShipmentsRequest
	5,  // 8: shipment.ShipmentService.CreateShipment:input_type -> shipment.CreateShipmentRequest
	7,  // 9: shipment.ShipmentService.UpdateShipment:input_type -> shipment.UpdateShipmentRequest
	9,  // 10: shipment.ShipmentService.DeleteShipment:input_type -> shipment.DeleteShipmentRequest
	11, // 11: shipment.ShipmentService.GetRates:input_type -> shipment.GetRatesRequest
	4,  // 12: shipment.ShipmentService.GetShipments:output_type -> shipment.GetShipmentsResponse
	6,  // 13: shipment.ShipmentService.CreateShipment:output_type -> shipment.CreateShipmentResponse
	8,  // 14: shipment.ShipmentService.UpdateShipment:output_type -> shipment.UpdateShipmentResponse
	10, // 15: shipment.ShipmentService.DeleteShipment:output_type -> shipment.DeleteShipmentResponse
	12, // 16: shipment.ShipmentService.GetRates:output_type -> shipment.GetRatesResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_shipment_proto_init() }
func file_proto_shipment_proto_init() {
	if File_proto_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shipment_proto_rawDesc), len(file_proto_shipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shipment_proto_goTypes,
		DependencyIndexes: file_proto_shipment_proto_depIdxs,
		MessageInfos:      file_proto_shipment_proto_msgTypes,
	}.Build()
	File_proto_shipment_proto = out.File
	file_proto_shipment_proto_goTypes = nil
	file_proto_shipment_proto_depIdxs = nil
}
