package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/Tanmoy095/LogiSynapse/graphql-gateway/graph/generated"
	"github.com/Tanmoy095/LogiSynapse/graphql-gateway/graph/model"
)

// Now implement Query resolver methods on queryResolver
func (r *queryResolver) Shipments(ctx context.Context, origin *string) ([]*model.Shipment, error) {
	allShipments := []*model.Shipment{
		{
			ID:          "1",
			Status:      "In Transit",
			Origin:      "Dhaka",
			Destination: "Berlin",
			Eta:         "2025-07-15",
			Carrier: &model.Carrier{
				Name:        "DHL",
				TrackingURL: "https://dhl.com/track/123",
			},
		},
		{
			ID:          "2",
			Status:      "Delivered",
			Origin:      "Chittagong",
			Destination: "Munich",
			Eta:         "2025-07-10",
			Carrier: &model.Carrier{
				Name:        "DHL",
				TrackingURL: "https://dhll.com/track/123",
			},
		},
	}

	// If no origin is provided, return all
	if origin == nil {
		return allShipments, nil
	}

	// Filter by origin
	var filtered []*model.Shipment
	for _, shipment := range allShipments {
		if shipment.Origin == *origin {
			filtered = append(filtered, shipment)
		}
	}

	return filtered, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
